version: "3.9"

services:
  app_development:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      FASTIFY_SERVER_HOST: ${FASTIFY_SERVER_HOST}
      FASTIFY_SERVER_PORT: ${FASTIFY_SERVER_PORT}
      JWT_TOKEN: ${JWT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${FASTIFY_SERVER_PORT}:${FASTIFY_SERVER_PORT}
    depends_on:
      - postgres
    profiles:
      - development
  app_production:
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file:
      - .env
    environment:
      FASTIFY_SERVER_HOST: ${FASTIFY_SERVER_HOST}
      FASTIFY_SERVER_PORT: ${FASTIFY_SERVER_PORT}
      JWT_TOKEN: ${JWT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${FASTIFY_SERVER_PORT}:${FASTIFY_SERVER_PORT}
    depends_on:
      - postgres
    profiles:
      - production
  postgres:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=docker
