name: Code Style Check

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Check prettier and eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Check eslint
        run: npm run lint